# Generated by Django 5.0.1 on 2024-02-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('columns', models.JSONField()),
            ],
            options={
                'unique_together': {('model_id', 'type')},
            },
        ),
    ]
